stages:
  - build

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/codesigntheory/django-base:latest -t registry.gitlab.com/codesigntheory/django-base:3.7 ./
    - docker push registry.gitlab.com/codesigntheory/django-base:latest
    - docker push registry.gitlab.com/codesigntheory/django-base:3.7
  tags:
    - docker
    - build
  only:
    refs:
      - master
