stages:
  - build

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/codesigntheory/django-base:latest -t registry.gitlab.com/codesigntheory/django-base:3.8 ./
    - docker push registry.gitlab.com/codesigntheory/django-base:latest
    - docker push registry.gitlab.com/codesigntheory/django-base:3.8
  tags:
    - docker
    - build
  only:
    refs:
      - master


build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/codesigntheory/django-base:$CI_COMMIT_REF_NAME ./
    - docker push registry.gitlab.com/codesigntheory/django-base:$CI_COMMIT_REF_NAME
  tags:
    - docker
    - build
  except:
    refs:
      - master
